[package]

name = "kronecker"
version = "0.1.0"
description = "Provides Kronecker Delta Function"
keywords = ["delta", "kronecker", "difference", "equal", "different"]

authors = ["Daniel Slocombe <ds4314@ic.ac.uk>"]
repository = "https://github.com/danslocombe/rust-kronecker"
license = "MIT"
